### ISSUE TITLE
More functions

### ISSUE THREAD

**Issue by pjebs** [Sandertv/go-formula#1]
Can I add more built-in functions.

I can do a PR with more functions from the math package

**Comment by Sandertv** [comment]
Sure thing, please feel free.

**Comment by pjebs** [comment]
Also what about unlimited arguments. Max should allow unlimited.

That would be a bigger change

**Comment by Sandertv** [comment]
I'll look into implementing that.

**Comment by pjebs** [comment]
Addressed here: https://github.com/Sandertv/go-formula/pull/2

**Comment by Sandertv** [comment]
Resolved in 75762d1872d075a931565881ace3650ee59d086b.
