### ISSUE TITLE
Traffic

### ISSUE THREAD

**Issue by pjebs** [Sandertv/go-formula#12]
Can you please send me the traffic information for this package.

Insights -> Traffic -> Git clones and visitors.

**Comment by Sandertv** [comment]
![image](https://user-images.githubusercontent.com/16114089/85535410-719cf600-b612-11ea-8abd-b02d03b86df2.png)
![image](https://user-images.githubusercontent.com/16114089/85535438-795c9a80-b612-11ea-8197-551fc23e253c.png)
