### ISSUE TITLE
NaN returned instead of 0 if func doesn't have enough args.

### ISSUE THREAD

**Issue by pjebs** [Sandertv/go-formula#3]
For V2 can we  make this change?

**Comment by Sandertv** [comment]
That sounds like a reasonable change.

**Comment by pjebs** [comment]
Can you change it?

**Comment by Sandertv** [comment]
Yep, give me a couple of minutes.

**Comment by Sandertv** [comment]
I assume variables/functions that don't exist, would also be more preferable to resolve to NaN?

**Comment by Sandertv** [comment]
I have made functions/variables that don't exist and functions with too few arguments resolve to NaN in 2.0.0-alpha.1. Please try that and see if you have any other ideas on how it should be improved.

**Comment by pjebs** [comment]
Looks good.

Can you make go.mod minimum comparability to go1.12?

**Comment by pjebs** [comment]
I think some doc's need changing too re NaN

**Comment by Sandertv** [comment]
Yep, will do that.

**Comment by Sandertv** [comment]
Please check 2.0.0-alpha.2.
